### ISSUE TITLE
Activated GitHub Pages display

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2022#1]
@mgrover1 @scollis 

I've activated the pages display of https://openradarscience.org/erad2022.

Could you elaborate how this repo fits with that one https://github.com/MeteoSwiss/ERAD-Open_Source-Radar-2022? Are they meant to be used in combination?

We would also need to at least claim that we use the project pythia cookbook-template and maybe adapt the links to other parties. ATM it looks like this belongs directly to Project Pythia.

**Comment by mgrover1** [comment]
Thanks for bringing up those points - let's just use the repo over there then. The reason for using the template is that it came with the additional infrastructure/such, but we can modify the existing ERAD 2022 repo over in Meteoswiss with those infrastructure elements. 

Perhaps we can transfer that other repo here so they are all in the same place?

**Comment by wolfidan** [comment]
Ciao, 
Sorry about that, let's transfer the repo at MeteoSwiss here. I will merge the two now.
Thanks

**Comment by mgrover1** [comment]
No worries! I should have reached out to ya'll first :)

**Comment by kmuehlbauer** [comment]
@mgrover1  I've activated discussions.
