### ISSUE TITLE
Install baltrad into book environment

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2022#18]
If we want to automatically run the notebooks which are using baltrad on book build, we need to install baltrad into that environment too. That is different from the binder, but we can use the same procedure there.

**Comment by kmuehlbauer** [comment]
We would also need to pull the baltrad notebooks to have them on book build time.

**Comment by DanielMichelson** [comment]
@kmuehlbauer please explain what the "book environment" is. I have noted that the baltrad_short_course Jupyter notebooks have installed, and that the one I checked seems to work through the browser, so that's a good start. The notebooks will probably need a little updating to become current. The notebooks are run interactively, so are you referring to automated capabilities with the book env?

**Comment by kmuehlbauer** [comment]
@DanielMichelson Yes, there is one environment which is used with binder. And there is another environment which is run via GitHub Actions (book environment). This creates the current website (see repo main site on the right, there is a link).

We would need to run the same procedure in GitHub Actions, which we now run in binder.

Does that make sense?

**Comment by DanielMichelson** [comment]
You're referring to the notebook content on the course website: https://openradarscience.org/erad2022/ ?
This makes sense to me. Is the objective to enable all the notebooks we have? There is only a handful of BALTRAD notebooks, so I hope this does not involve too much extra effort.

**Comment by kmuehlbauer** [comment]
Exactly, I was referring to the course website.

In my opinion it would be great, if the course website would have the same content what would be available on binder. 

From my current experience the additional build cost with regard to time is not that big of a deal. The environment can also be cached IIRC.

**Comment by kmuehlbauer** [comment]
It would be most wanted if we could just use the baltrad install process for both binder and book environment. Same would be true for the data parts of the other packages.

**Comment by mgrover1** [comment]
We can likely add a few additional lines to the `build-book.yml` file, calling the `postBuild` script, placing that line after the environment build but before the book build.

**Comment by kmuehlbauer** [comment]
@mgrover1 Yes, something along these lines.

I've tested (successfully) installing locally (as GHA would do) into conda env. But we need more tweaks to the install scripts to work transparently on binder, GHA and locally.

I need to finalize this, but if you are eager to look, the WIP is in my fork (
https://github.com/kmuehlbauer/erad2022/tree/local-baltrad).
