### ISSUE TITLE
build docker image on GHA

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2022#28]
As discussed at the dev meeting it would be great to build the binder image on GHA.

The workflow could be something like this:

1. use repo2docker (as mentioned in #23) and build the image as part of some GHA workflow
1. use that Dockerimage [here](https://github.com/openradar/erad2022/tree/main/binder)
1. start a container from that image and run a bunch of tests inside nad/or even build the book in there

The fist two points should just work, we only need to agree where to push that image to (quay.io ?). I'm sure we can get point 3 to work.

I'll try to set something up. @mgrover1 Please chime in with any ideas from your side.

Update:

OK, here we go. With #30 and #31 and some changes to the org package permissions everything should work as outlined above. It uses ghcr.io, github package registry. This should work in any case on PUSH (already tested) and also for PULL REQUESTS (now that the package is created). But we need to check!

Update2:

With #32 a special workflow for pull requests was introduced. Within this workflow the docker image is built and used for book building.

**Comment by mgrover1** [comment]
Using the repo2docker action sounds like a good plan!

**Comment by kmuehlbauer** [comment]
OK, it looks like we need to set some more things.

In #31 "openradar" is used as package index endpoint. Let's see, if this works. If not we would need to fiddle with the secrets and possibly use a PAT.

**Comment by kmuehlbauer** [comment]
@mgrover1 We have a working setup now :rocket:. Could you check with a simple PULL Request if this works in PR's too? If this works we can close this one.

For all binder sessions the new docker image available at https://github.com/openradar/erad2022/pkgs/container/erad2022 should now be used automatically. And everyone can just fire up a container based on that image and has a running jupyterlab including the latest state of this repo.

**Comment by mgrover1** [comment]
Great @kmuehlbauer !! Thank you!! I opened a PR (#32 ) to test this out

**Comment by kmuehlbauer** [comment]
One good news, the nightly build just worked and a new image was pushed to the registry.

**Comment by kmuehlbauer** [comment]
Going to close this as resolved by #30, #31 and #32.
