### ISSUE TITLE
Add pyrad in Docker installation

### ISSUE THREAD

**Issue by wolfidan** [openradar/erad2022#45]
Hi everybody,

I was wondering if we could install pyrad on our binder for the course. 
The command is 
conda install -c conda-forge pyrad_mch (see https://anaconda.org/conda-forge/pyrad_mch)

Thanks a lot,
Cheers,
Daniel

**Comment by kmuehlbauer** [comment]
We would need to add it to both the environment.yml files. 

- https://github.com/openradar/erad2022/blob/main/environment.yml
- https://github.com/openradar/erad2022/blob/main/binder/environment.yml

**Comment by wolfidan** [comment]
Thanks @kmuehlbauer , should I do a PR?

**Comment by kmuehlbauer** [comment]
Yes, that would be OK. You are using this in the pyrad notebooks, right?

**Comment by wolfidan** [comment]
@kmuehlbauer , yes, I will show a pyrad example at the end of the pyart notebooks.

**Comment by kmuehlbauer** [comment]
Then it should added, otherwise it won't work.

**Comment by kmuehlbauer** [comment]
solved by #46
