### ISSUE TITLE
Error in Binder docker build

### ISSUE THREAD

**Issue by wolfidan** [openradar/erad2022#5]
Ciao @mgrover1,

I wanted to test the binder but when generating the docker (https://mybinder.org/v2/gh/openradar/erad2022/main?urlpath=https%3A%2F%2Fgithub.com%2Fopenradar%2Ferad2022%2Fblob%2Fmain%2Fnotebooks%2Fnotebook-template.ipynb), I run into the following error:

_Installing pip dependencies: ...working... Pip subprocess error:
  Running command git clone --filter=blob:none --quiet https://github.com/ARM-DOE/pyart.git /tmp/pip-req-build-6_2bfw8_
  Running command git clone --filter=blob:none --quiet https://github.com/openradar/PyDDA.git /tmp/pip-req-build-a3yf3t6z
  Running command git clone --filter=blob:none --quiet https://github.com/CSU-Radarmet/CSU_RadarTools.git /tmp/pip-req-build-kjiofhml
ERROR: Ignored the following versions that require a different python version: 0.21.0 Requires-Python >=3.8; 0.21.1 Requires-Python >=3.8; 2022.3.0 Requires-Python >=3.8; 2022.6.0rc0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement xarray>=0.21.1 (from arm-pyart) (from versions: 0.7.0, 0.7.1, 0.7.2, 0.8.0rc1, 0.8.0, 0.8.1, 0.8.2, 0.9.0rc1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.10.0rc1, 0.10.0rc2, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.20.0, 0.20.1, 0.20.2)
ERROR: No matching distribution found for xarray>=0.21.1_

Apparently python3.7 is being installed which is not compatible with the later xarray versions. Did it work for you?
Thanks

**Comment by mgrover1** [comment]
Yeah - we need to figure out how to get the environment running properly. I am thinking we can simplify it for now, and add more as we need. I think pinning a specific python version would help with that.

**Comment by mgrover1** [comment]
@wolfidan - I got the build working with the updated environment/setup files in #6 !
