### ISSUE TITLE
Missing subset_radar in pyART

### ISSUE THREAD

**Issue by wolfidan** [openradar/erad2022#55]
Hello @mgrover1 ,

I'm really sorry for pushing this, but do you think it would be possible to release a new *arm_pyart* conda package until the course.?Because pyrad relies on the availability of the *subset_radar* function which is in now in the master of *arm_pyart* but not yet in the conda package.

Thank you very much,
Cheers,
Daniel

**Comment by mgrover1** [comment]
That is the plan! I will ping you once we cut that release
