### ISSUE TITLE
Final Actions

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2022#59]
With #58 everything should be in place for the ERAD 2022 course. Hooray! :tada:

This issue should keep track of any remaining actions, please extend.

## Website Display Check [openradar/erad2022](https://openradarscience.org/erad2022/README.html)

- [x] Introductions and Overview
- [x] Baltrad Tutorial
- [x] LROSE Tutorial
- [x] Py-ART Tutorial
- [x] wradlib Tutorial
- [x] Open Radar Workflows
    - [x] baltrad2wradlib
    - [x] baltrad_pyart_rain_rate
    - [x] pyart_baltrad_dealias
- [x] Becoming a developer

## Binder processing check [binder-link](https://aws-uswest2-binder.pangeo.io/v2/gh/openradar/erad2022/main?labpath=notebooks)

- [x] Baltrad Tutorial
- [x] LROSE Tutorial
- [x] Py-ART Tutorial
- [x] wradlib Tutorial
- [x] Open Radar Workflows
    - [x] baltrad2wradlib
    - [x] baltrad_pyart_rain_rate
    - [x] pyart_baltrad_dealias

## Current bugs/pitfalls

- [ ] saving processed notebooks sometimes fails with `invalid response 413 request entity too large`
    - temporary workaround: deactivate automatic saving in the lab settings

**Comment by kmuehlbauer** [comment]
@openradar/erad2022-team it would be great, if everyone can have a look at website and binder to check if everything works so far. Just mark the boxes for your respective parts. Thanks!

**Comment by wolfidan** [comment]
@kmuehlbauer , thanks, I just checked my pyart notebooks and the pyrad config files and they work perfectly! :) :). I will just let the other pyart people check the two other notebooks (pyart_basic and pyart_gridding) since I'm not their author, and we can then check the pyart box.

**Comment by mike-dixon** [comment]
Hi Kai
I was able to run the LROSE notebook all the way through. No problems.
Thank you for all of your help.
And thanks to Max for giving me a tutorial on how to use binder and get my
stuff checked in.
Mike

**Comment by kmuehlbauer** [comment]
@mike-dixon Great! I've checked the boxes for LROSE.

**Comment by mgrover1** [comment]
Tested the Py-ART notebooks this morning - all good to go!

**Comment by kmuehlbauer** [comment]
Then baltrad is the last to check. It looks like, that all notebooks work. I've specifically checked the baltrad2wradlib notebook which works as expected. Also run all the other baltrad related notebooks, which run fine. Only in one notebook CAPPI's should be created from the command line and those files are not available for plotting. Maybe @DanielMichelson can confirm proper functionality?

**Comment by DanielMichelson** [comment]
Confirming! All good, except perhaps the dealiasing notebook in the pyart2baltrad project, but we knew that already. No biggie.

**Comment by kmuehlbauer** [comment]
We can leave this issue open and add items to the list, if they come up.

**Comment by kmuehlbauer** [comment]
I've problems with binder to save a processed notebook, get `invalid response 413 request entity too large` error. Not a big deal either, just have to deactivate autosave. I'll add it to the list.

**Comment by mgrover1** [comment]
One other thing I would like to add are the presentations (rendered directly on the webpage). I am still working on finalizing a few more slides for the Open Science part, so once that is good to go (and I confirm with @DanielMichelson ), I can upload those + add those to the pages.

**Comment by kmuehlbauer** [comment]
@mgrover1 Yes, sure, put it on the list. :+1:

**Comment by mgrover1** [comment]
What do ya'll think of this graphic? Planning on using it during the open science presentation - highlighting interoperability in the open radar community

 (@kmuehlbauer @DanielMichelson @mike-dixon @wolfidan )
![Screen Shot 2022-08-24 at 10 28 33 AM](https://user-images.githubusercontent.com/26660300/186459284-aed3401f-0d18-44ac-825a-bb1d07a6733c.png)

**Comment by mike-dixon** [comment]
Hi Max
You could perhaps add CfRadial alongside PyArt Radar for data models, since
the PyArt approach is based on CfRadial?
Mike

**Comment by kmuehlbauer** [comment]
This can be closed, too. I'll open a new issue for the remaining bug with our workaround.
