### ISSUE TITLE
Infrastructure Guide

### ISSUE THREAD

**Issue by mgrover1** [openradar/erad2022#65]
As was mentioned during the meeting on Saturday, it would be useful to compile an infrastructure guide walking through:
- [x] How the environment was built for this course
- [x] Which tools were used to build + render the notebooks
- [ ] How one can apply this to another short course

Feel free to add other ideas!

**Comment by kmuehlbauer** [comment]
Here are my notes on the workflow. I'll revisit and add it to the getting started guide later.

https://github.com/openradar/erad2022/discussions/34

**Comment by mgrover1** [comment]
Closing this now that this has all been merged
