### ISSUE TITLE
Example datasets

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/erad2022#9]
How should we make example datasets available which will be used with the notebooks? 

Which datasets are already available in the build process?

- [x] baltrad (build time)
- [x] wradlib (repo/runtime)
- [x] pyart/pyrad (repo/runtime)
- [x] lrose (runtime)

**Comment by mgrover1** [comment]
Yeah! We can add a bash script to download via http or ftp, and we can add a `/data` directory

**Comment by mgrover1** [comment]
With #35 , we now have some sample data from meteoswiss in the the `/data` directory!

**Comment by kmuehlbauer** [comment]
@mgrover1 @wolfidan I'll try to reuse some of the data you've provided, if that's OK with you.

**Comment by wolfidan** [comment]
@kmuehlbauer 
Sure, that's great, thanks!

**Comment by DanielMichelson** [comment]
I agree! No problem using any data I have provided.

**Comment by mgrover1** [comment]
@kmuehlbauer do you have all the datasets you need for the wradlib tutorial portion?

**Comment by kmuehlbauer** [comment]
I'm fixing up my notebooks tomorrow. I will reuse some of the already distributed data. But will issue a PR with some more data (< 40 MB) with the same PR tomorrow.

**Comment by mgrover1** [comment]
Sounds good!!

**Comment by mgrover1** [comment]
@mike-dixon which data were you thinking of using for LROSE?

**Comment by kmuehlbauer** [comment]
I think we've good to close this. All data is either available in the repo, will be pulled in at build time or at runtime.
